### ISSUE TITLE
How to continue with the package of the day?

### ISSUE THREAD

**Issue by samcarter** [samcarter/PackageOfTheDay#11]
The package of the day will soon complete its one year cycle. I’d like to hear your opinion on how to proceed. Please thumbup one of the suggestions below or leave a comment if you have other ideas.

**Comment by samcarter** [comment]
- stop it, maybe do something new

**Comment by samcarter** [comment]
- keep going, but in a reduced frequency (I don’t have enough ideas left to keep the daily rhythm)

**Comment by samcarter** [comment]
- keep going as it is, we will contribute enough ideas to fill it daily

**Comment by LucaPolese** [comment]
> * keep going, but in a reduced frequency (I don’t have enough ideas left to keep the daily rhythm)

Package\Packages of the month?

**Comment by samcarter** [comment]
@LucaPolese  .. or week. I think my "package-discovery-rate" would be high enough for weekly posts

**Comment by samcarter** [comment]
@all Thank you all for your input about the future of the package of the day: I will continue at irregular intervals, whenever I come across something that is interesting. 

If you have any suggestions for packages or tools to be featured, please let me know at https://github.com/samcarter/PackageOfTheDay/issues/12
