### ISSUE TITLE
atendofenv

### ISSUE THREAD

**Issue by CarLaTeX** [samcarter/PackageOfTheDay#4]
I'd like to suggest: https://ctan.mirror.garr.it/mirrors/ctan/macros/latex/contrib/atendofenv/atendofenv.pdf

**Comment by samcarter** [comment]
Great suggestion - thanks!

**Comment by CarLaTeX** [comment]
You're welcome!

Il Sab 26 Feb 2022, 11:58 samcarter ***@***.***> ha scritto:
